apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: atom
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /
      prometheus.io/port:   '8080'
spec:
  selector: 
    app: jenkins-server
  externalTrafficPolicy: Local
  type: LoadBalancer
  ports:
    - name: jenkins
      port: 8080
      targetPort: 8080
      nodePort: 32000
    - name: jenkins-slave
      port: 50000
      protocol: TCP
      targetPort: 50000
